# Generated by Django 4.2.7 on 2024-02-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_contactus_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'توضیحات صفحه درباره', 'verbose_name_plural': 'توضیحات های صفحه درباره ما'},
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='imge',
        ),
    ]
