# Generated by Django 4.2.7 on 2024-02-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_contactus_options_remove_contactus_imge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
    ]
