# Generated by Django 4.2.7 on 2024-02-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_us_team_options_us_team_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='us_team',
            name='email',
            field=models.EmailField(blank=True, editable=False, help_text='<h3 style="color: #0a58ca" class="help">برای تغیر ایمیل به بخش کاربر ها رفته و ایمیل کاربر مورد نظر خود را تغیر دهید<h3>', max_length=254, null=True, verbose_name='ایمیل'),
        ),
    ]
