# Generated by Django 4.2.7 on 2024-02-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_message_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code_Password_Recovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=5, verbose_name='کد')),
            ],
            options={
                'verbose_name': 'کد بخش فراموشی رمز',
                'verbose_name_plural': 'کد های بخش فراموشی رمز',
            },
        ),
    ]
