# Generated by Django 4.2.7 on 2024-02-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_code_password_recovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_password_recovery',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
