# Generated by Django 4.2.7 on 2024-02-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_code_password_recovery_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_password_recovery',
            name='expiration_time',
            field=models.TimeField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AddField(
            model_name='code_password_recovery',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='ایا این کد قابل استفاده هست ؟'),
        ),
        migrations.AlterField(
            model_name='code_password_recovery',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
    ]
