# Generated by Django 4.2.7 on 2024-02-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_address_ostan_address_shahr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ostan',
            field=models.CharField(default='', max_length=20, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.IntegerField(max_length=12, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='address',
            name='shahr',
            field=models.CharField(default='', max_length=20, verbose_name='شهر'),
        ),
    ]
