# Generated by Django 4.2.7 on 2024-02-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='fullname',
            field=models.CharField(max_length=40, verbose_name='نام و نام خانوادگی گیرنده '),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='تلفن فرد گیرنده'),
        ),
    ]
