# Generated by Django 4.2.7 on 2024-02-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_address_fullname_alter_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ostan',
            field=models.CharField(default='', help_text=[('تهران', 'تهران'), ('مشهد', 'مشهد')], max_length=20, verbose_name='استان'),
        ),
    ]
