# Generated by Django 4.2.7 on 2024-02-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_state_alter_city_options_remove_city_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='ostan',
        ),
        migrations.RemoveField(
            model_name='address',
            name='shahr',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.city', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.state', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='نام شهر'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.state', verbose_name='استان والد'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='نام استان'),
        ),
    ]
