# Generated by Django 4.2.7 on 2024-03-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_remove_person_city_remove_person_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False, verbose_name='آدرس پیشفرض'),
        ),
    ]
