# Generated by Django 4.2.7 on 2024-02-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقاله ها'},
        ),
        migrations.AddField(
            model_name='blog',
            name='short_body',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='بدنه کوچک شده'),
        ),
    ]
