# Generated by Django 4.2.7 on 2024-02-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_blog_short_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_body',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='بدنه کوچک شده'),
        ),
    ]
