# Generated by Django 4.2.7 on 2024-02-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_short_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=0, verbose_name='امار بازدید'),
        ),
    ]
