# Generated by Django 4.2.7 on 2024-03-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_products_tag'),
        ('blog', '0011_alter_blog_body_alter_blogcomment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(to='products.tag', verbose_name='تگ'),
        ),
    ]
