# Generated by Django 4.2.7 on 2024-02-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='جواب')),
            ],
            options={
                'verbose_name': 'سوالات متداول',
                'verbose_name_plural': 'سوالات های متداول',
            },
        ),
    ]
