# Generated by Django 4.2.7 on 2024-02-28 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_alter_categorytitles_options'),
        ('cart', '0002_alter_order_is_paid_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.memory', verbose_name='حافظه'),
        ),
    ]
