# Generated by Django 4.2.7 on 2024-03-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_total_discount_order_total_price_af_dis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='شناسه کد تخفیف')),
                ('discount', models.SmallIntegerField(default=0, verbose_name='مقدار تخفیف')),
                ('quantity', models.SmallIntegerField(default=1, verbose_name='تعداد باقیمانده معتبر')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد های تخفیف',
            },
        ),
    ]
