# Generated by Django 4.2.7 on 2024-03-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_discount_code',
            field=models.CharField(blank=True, default=0, max_length=100, null=True, verbose_name='جمع تخفیف کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
    ]
