# Generated by Django 4.2.7 on 2024-03-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_total_discount_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_discount_code',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='جمع تخفیف کد تخفیف'),
        ),
    ]
