# Generated by Django 4.2.7 on 2024-03-01 18:09

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_order_total_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True),
        ),
    ]
