# Generated by Django 4.2.7 on 2024-02-02 07:39

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('star_ratings', '0004_alter_rating_id_alter_userrating_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'رتبه بندی محصول', 'verbose_name_plural': 'رتبه بندی محصول ها'},
        ),
        migrations.AlterModelOptions(
            name='userrating',
            options={'verbose_name': 'رتبه بندی کاربر', 'verbose_name_plural': 'رتبه بندی کاربران'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='average',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6, verbose_name='میانگین'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد نظر'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='جمع ستاره ها'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='ip ادرس'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to=settings.STAR_RATINGS_RATING_MODEL, verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='score',
            field=models.PositiveSmallIntegerField(verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
