# Generated by Django 4.2.7 on 2023-12-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_images_product_images_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='product',
        ),
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.ManyToManyField(to='products.images', verbose_name='تصاویر'),
        ),
    ]
