# Generated by Django 4.2.7 on 2024-01-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_color_color_alter_products_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='f_color',
        ),
    ]
