# Generated by Django 4.2.7 on 2024-01-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_color_f_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='f_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
