# Generated by Django 4.2.7 on 2024-01-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_color_color_alter_products_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='products.color', verbose_name='رنگ'),
        ),
    ]
