# Generated by Django 4.2.7 on 2024-01-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_memory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='memory',
        ),
        migrations.AddField(
            model_name='products',
            name='memory',
            field=models.ManyToManyField(blank=True, null=True, to='products.memory', verbose_name='حافظه'),
        ),
    ]
