# Generated by Django 4.2.7 on 2024-01-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_products_memory_products_memory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name': 'حافظه', 'verbose_name_plural': 'حافظه ها'},
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'توضیحات',
                'verbose_name_plural': 'توضیحات ها',
            },
        ),
    ]
