# Generated by Django 4.2.7 on 2024-01-31 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_products_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='views',
        ),
    ]
