# Generated by Django 4.2.7 on 2024-01-31 17:54

from django.db import migrations, models
import hitcount.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_products_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
