# Generated by Django 4.2.7 on 2024-01-31 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_g'),
    ]

    operations = [
        migrations.DeleteModel(
            name='G',
        ),
    ]
