# Generated by Django 4.2.7 on 2024-02-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_delete_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='namne',
            field=models.TextField(blank=True, null=True),
        ),
    ]
