# Generated by Django 4.2.7 on 2024-02-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_products_namne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='namne',
        ),
    ]
