# Generated by Django 4.2.7 on 2024-02-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_products_views_delete_productviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='امار بازدید'),
        ),
    ]
