# Generated by Django 4.2.7 on 2024-02-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_products_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='stars',
        ),
    ]
