# Generated by Django 4.2.7 on 2024-02-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_remove_products_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='available',
            field=models.BooleanField(default=True, verbose_name='کالا موجود است'),
        ),
    ]
