# Generated by Django 4.2.7 on 2024-02-08 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_products_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-id'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=uuid.uuid1, help_text='<h3 style="color: #0a58ca" class="help">ادرس بر اساس فیلد (عنوان مختصر) ساخته میشود<h3>', null=True, unique=True, verbose_name='آدرس'),
        ),
    ]
