# Generated by Django 4.2.7 on 2024-02-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_alter_products_options_alter_products_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
