# Generated by Django 4.2.7 on 2024-02-14 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_alter_products_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.mark', verbose_name='مارک'),
        ),
    ]
