# Generated by Django 4.2.7 on 2024-02-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_alter_products_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytitles',
            options={'verbose_name': 'سر فصل دسته بندی', 'verbose_name_plural': 'سر فصل دسته بندی ها'},
        ),
    ]
