# Generated by Django 4.2.7 on 2024-03-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_alter_categorytitles_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
    ]
