# Generated by Django 4.2.7 on 2024-03-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_alter_comment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
    ]
