# Generated by Django 4.2.7 on 2024-03-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_tag_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.ManyToManyField(to='products.tag', verbose_name='تگ'),
        ),
    ]
